[tool.black]
line-length = 80
target-version = ["py39"]
skip-string-normalization = false
skip-magic-trailing-comma = false
exclude = '''
/(
  \.git
 |\.venv
 |venv
 |build
 |dist
 |__pycache__
)/'''

